/*
 * =====================================================================================
 *
 *       Filename:  p002.c
 *
 *    Description:  Project Euler Problem 2
 *
 *    Each new term in the Fibonacci sequence is generated by adding the
 *    previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *    By considering the terms in the Fibonacci sequence whose values do not
 *    exceed four million, find the sum of the even-valued terms.
 *
 *        Version:  1.0
 *        Created:  04/17/2016 10:04:27 AM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Seth Lienemann (sal), sethlienemann@gmail.com
 *   Organization:  
 *
 * =====================================================================================
 */


#include    <stdint.h>
#include    <stdio.h>
#include	<stdlib.h>
#define     LIMIT (4000000)

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  main
 *  Description:  
 * =====================================================================================
 */
int main 
    ( 
    int argc, 
    char *argv[] 
    )
{
uint32_t fibonacci_val = 2;
uint32_t prev_val = 1;
uint32_t temp_val = 0;
uint32_t ret_val = 0;
while( fibonacci_val < LIMIT )
    {
    /* if even */
    if((fibonacci_val & 0x01) == 0)
        {
        ret_val += fibonacci_val;
        }
    /* Update the fibonacci values */
    temp_val = fibonacci_val + prev_val;
    prev_val = fibonacci_val;
    fibonacci_val = temp_val;
    }

printf("The answer is: %d\n", ret_val);
return EXIT_SUCCESS;
}				/* ----------  end of function main  ---------- */

